.code
; init input & output ports
	ld r19, 0
	ld r18, 1
; read dimension
	in r1, r19
; n squared
	mul r2, r1, r1
; element size 8 bytes
	ld r3, 8
; compute total size
	mul r4, r2, r3
; A base = 65536
	ld r8, 65536
; set B base
	add r9, r8, r4
; set C base
	add r10, r9, r4
; A loading index
	clr r5
; load A
:inputA
	in r6, r19
	mul r7, r5, r3
	add r7, r8, r7
	mov (r7)(0), r6
	addi r5, 1
	sub r7, r2, r5
	ld r20, :inputA
	brnz r20, r7
; B loading index
	clr r5
; load B
:inputB
	in r6, r19
	mul r7, r5, r3
	add r7, r9, r7
	mov (r7)(0), r6
	addi r5, 1
	sub r7, r2, r5
	ld r20, :inputB
	brnz r20, r7
; init outer loop i
	clr r11
; outer loop
:loopi
; init middle loop j
	clr r12
; middle loop
:loopj
; init C[i][j] to 0.0
	clr r13
; init inner loop k
	clr r14
; inner loop
:loopk
; A[i][k] = base_A + (i*n + k)*8
	mul r15, r11, r1
	add r15, r15, r14
	mul r15, r15, r3
	add r15, r8, r15
	mov r15, (r15)(0)
; B[k][j] = base_B + (k*n + j)*8
	mul r16, r14, r1
	add r16, r16, r12
	mul r16, r16, r3
	add r16, r9, r16
	mov r16, (r16)(0)
; A[i][k] * B[k][j] as double
	mulf r17, r15, r16
; add product
	addf r13, r13, r17
; k++ and check k < n
	addi r14, 1
	sub r7, r1, r14
	ld r20, :loopk
	brnz r20, r7
; C[i][j] = base_C + (i*n + j)*8
	mul r15, r11, r1
	add r15, r15, r12
	mul r15, r15, r3
	add r15, r10, r15
; store in C[i][j]
	mov (r15)(0), r13
; j++ and check j < n
	addi r12, 1
	sub r7, r1, r12
	ld r20, :loopj
	brnz r20, r7
; i++ and check i < n
	addi r11, 1
	sub r7, r1, r11
	ld r20, :loopi
	brnz r20, r7
; output index
	clr r5
; output C
:outputloop
	mul r7, r5, r3
	add r7, r10, r7
	mov r6, (r7)(0)
	out r18, r6
	addi r5, 1
	sub r7, r2, r5
	ld r20, :outputloop
	brnz r20, r7
; halt
	halt
.data
	0